'use strict';
const bcrypt = require('bcrypt');

module.exports = {
	async up(queryInterface, Sequelize) {
		await queryInterface.bulkInsert('people', [
			{
				name: 'Admin',
				last_name: 'Admin last name',
				email: 'admin@gmail.com',
				date_birth: new Date(),
				address: 'Av. Siempre Viva',
				cellphone: '76565432',
				username: 'Admin',
				password: await bcrypt.hash('12345678', 10),
				id_rol: 1,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				name: 'Carlos',
				last_name: 'Torres',
				email: 'docente1@gmail.com',
				date_birth: new Date(),
				address: 'Av. Siempre Viva',
				cellphone: '76565432',
				ci_number: '123',
				ci_expedition: 'CH',
				username: 'docente1',
				password: await bcrypt.hash('76565432', 10),
				id_rol: 2,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				name: 'Marcelo',
				last_name: 'Vargas',
				email: 'docente2@gmail.com',
				date_birth: new Date(),
				address: 'Av. Siempre Viva',
				cellphone: '77112939',
				username: 'docente2',
				ci_number: '122',
				ci_expedition: 'LP',
				password: await bcrypt.hash('77112939', 10),
				id_rol: 2,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				name: 'Juan',
				last_name: 'Perez',
				email: 'docente3@gmail.com',
				date_birth: new Date(),
				address: 'Av. Siempre Viva',
				cellphone: '76565432',
				ci_number: '12233',
				ci_expedition: 'CH',
				username: 'docente3',
				password: await bcrypt.hash('76565432', 10),
				id_rol: 2,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				name: 'Monica',
				last_name: 'Cruz Perez',
				email: 'docente4@gmail.com',
				date_birth: new Date(),
				address: 'Av. Siempre Viva',
				cellphone: '88776654',
				username: 'docente4',
				ci_number: '11221',
				ci_expedition: 'CH',
				password: await bcrypt.hash('88776654', 10),
				id_rol: 2,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				name: 'Maria Jose',
				last_name: 'Ruiz',
				email: 'coordinador1@gmail.com',
				date_birth: new Date(),
				address: 'Av. Siempre Viva',
				cellphone: '12345678',
				username: 'coordinador1',
				ci_number: '1111',
				ci_expedition: 'CH',
				password: await bcrypt.hash('12345678', 10),
				id_rol: 3,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				name: 'Coordinador 2',
				last_name: 'Lopez',
				email: 'coordinador2@gmail.com',
				date_birth: new Date(),
				address: 'Av. Siempre Viva',
				cellphone: '12345678',
				username: 'coordinador2',
				ci_number: '112345',
				ci_expedition: 'CH',
				password: await bcrypt.hash('12345678', 10),
				id_rol: 3,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				name: 'Juan Carlos',
				last_name: 'Lopez Poppe',
				email: 'coordinador3@gmail.com',
				date_birth: new Date(),
				address: 'Av. Siempre Viva',
				cellphone: '12345678',
				username: 'coordinador3',
				ci_number: '123456',
				ci_expedition: 'CH',
				password: await bcrypt.hash('12345678', 10),
				id_rol: 3,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				name: 'Juan Jose',
				last_name: 'Cueva',
				email: 'estudiante1@gmail.com',
				date_birth: new Date(),
				address: 'Av. Siempre Viva',
				cellphone: '12345678',
				username: 'estudiante1',
				ci_number: '1234567',
				ci_expedition: 'CH',
				password: await bcrypt.hash('12345678', 10),
				id_rol: 4,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				name: 'Carlos Marcelo',
				last_name: 'Torres Vargas',
				email: 'estudiante2@gmail.com',
				date_birth: new Date(),
				address: 'Av. Siempre Viva',
				cellphone: '12345678',
				username: 'estudiante2',
				ci_number: '12345678',
				ci_expedition: 'CH',
				password: await bcrypt.hash('12345678', 10),
				id_rol: 4,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				name: 'Estudiante 3',
				last_name: 'Torres Vargas',
				email: 'estudiante3@gmail.com',
				date_birth: new Date(),
				address: 'Av. Siempre Viva',
				cellphone: '12345678',
				username: 'estudiante3',
				ci_number: '876',
				ci_expedition: 'CH',
				password: await bcrypt.hash('12345678', 10),
				id_rol: 4,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				name: 'Luisa',
				last_name: 'Castro Dias',
				email: 'estudiante4@gmail.com',
				date_birth: new Date(),
				address: 'Av. Siempre Viva',
				cellphone: '12345678',
				username: 'estudiante4',
				ci_number: '87655',
				ci_expedition: 'CH',
				password: await bcrypt.hash('12345678', 10),
				id_rol: 4,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
		]);
	},

	async down(queryInterface, Sequelize) {
		await queryInterface.bulkDelete('people', null, {});
	},
};
